baseURL = "https://www.databrickssparkcertificationdumps.xyz"
disqusShortname = ""
googleAnalytics = "G-15PK4S7L6G"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Databricks Spark Certification Dumps - Exam Success + PDF"
[markup.goldmark.renderer]
unsafe = true
