author = "Databricks Spark Certification Dumps"
contact_form_action = "#"
description = ""
logo = "images/databricks_spark_certification_dumps.svg"
logo_width = "200px"
[navigation_button]
enable = true
label = "Get Started"
link = "https://bit.ly/sparkpracticeexams"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-graduation-cap"
link = "https://bit.ly/sparkpracticeexams"
title = "Databricks Certified Developer for Spark 3.0 Practice Exams"
